add validation that wellcomeprize can read.
philerooski/wellcome-surveillance-challenge pull request #1
Opened 2019-02-27 05:47 UTC by kdaily

2019-02-27 22:21 UTC, philerooski requested changes

2019-02-27 22:21 UTC, philerooski commented on workflows/scoring/validate.cwl
> +                    if "READ" not in perms:
DOWNLOAD

2019-02-27 22:21 UTC, philerooski commented on workflows/scoring/validate.cwl
> +                return invalid_reasons
newline

2019-02-27 22:21 UTC, philerooski commented on workflows/scoring/validate.cwl
> +                    invalid_reasons.append("User 'wellcomeprize' cannot read the project.")
`"User 'wellcomeprize' does not have DOWNLOAD permissions on {}".format(project_id)`

add team ID for wellcome eval panel

2019-02-27 22:21 UTC, philerooski commented on workflows/scoring/validate.cwl
> +                invalid_reasons += check_permissions(syn, sub)
Move immediately after syn.login

2019-02-27 23:04 UTC, kdaily commented on workflows/scoring/validate.cwl
> +                    if "READ" not in perms:
made it have both

2019-02-27 23:04 UTC, kdaily commented
Take a look again @philerooski, thanks!

2019-02-27 23:29 UTC, philerooski requested changes

2019-02-27 23:29 UTC, philerooski commented on workflows/scoring/validate.cwl
> +                        invalid_reasons.append("The evaluation panel team cannot read the project.")
Let's include the full team name here and down below: "Wellcome Data Re-use Prize - Surveillance Evaluation Panel". That way participants can copy paste into the web UI.

2019-02-28 20:20 UTC, philerooski approved these changes

2019-02-28 20:20 UTC, merged